apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    run: frontendapplication1
  name: frontendapplication
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend1
  template:
   metadata:
    labels:
      app: frontend
   spec:
    containers:
    - image: hub.docker.com/cubensquare/${BUILD_NUMBER}
      name: frontend
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  ports:
  - nodePort: 32000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend1
  sessionAffinity: None
  type: NodePort
