kind: Pod
apiVersion: v1
metadata:
  name: test
  labels:
    color: blue
    app: hdfc
  namespace: dev
spec:
tolerations:
- key: infra
  value: chennai
  effect: NoExecute
 containers:
 - name: test
   image: tomcat
   containerPort: 8080
   volumeMountPath:
   - name: volumetest123
     mountPath: /opt/tomcat/
 volumes:
 - name: volumetest123
   persistentvolumeClaim:
       claimName: cubensquare-pvc
       

