kind: Pod
apiVersion: v1
metadata:
  name: test
  labels:
    color: blue
  namespace: prod
spec:
 containers:
 - name: test
   image: tomcat
   containerPort: 8080
   volumeMounts:
   - name: testvolume
