kind: Pod
apiVersion: v1
metadata:
  name: test
  labels:
    color: blue
  namespace: prod
spec:
tolerations:
- key: infra
  value: node
  effect: NoSchedule
 containers:
 - name: test
   image: tomcat
   containerPort: 8080
   volumeMountPath:
   - name: volumetest123
     mountPath: /home/lokesh/
     mountPath: /home/goms/
 volumes:
 - name: volumetest123
   persistentvolumeClaim:
       claimName: cubensquare-pvc
       

